### ISSUE TITLE
For the gunmod holster thing

### ISSUE THREAD

**Issue by PGR-14** [FrontierMods/Armory#8]
In Relation to this: https://github.com/FrontierMods/Armory/blob/main/documentation/DESIRED_FEATURES.md#required-gunmods-for-holsters
You can have holsters only store an item if they have a flag, & you can give a gun a flag if they're modded (I.E. Bayonets).

This bayonet adds the flags below:
EX:
  {
    "id": "knife_combat_marine",
    "type": "TOOL",
    "category": "weapons",
    "name": { "str": "USMC bayonet" },
    "description": "A modern bayonet in use with the US Marine Corps, adopted in an effort to improve USMC hand-to-hand fighting capabilities.  The bayonet is optimized to function as a fighting knife, sporting an ergonomic handle that will minimize hand fatigue during combat.  The blade tip is sharper in profile than other bayonets to assist in penetrating body armor, and also features a small serrated section to provide for some utility.",
    "//": "Modelled after the OKC3S bayonet.",
    "weight": "405 g",
    "volume": "260 ml",
    "longest_side": "34 cm",
    "price": 10000,
    "price_postapoc": 1250,
    "to_hit": { "grip": "weapon", "length": "hand", "surface": "point", "balance": "good" },
    "material": [ "hc_steel", "plastic" ],
    "symbol": ";",
    "color": "dark_gray",
    "gunmod_data": {
      "location": "bayonet lug",
      "mod_targets": [ "pistol", "smg", "rifle", "shotgun", "launcher", "crossbow" ],
      "is_bayonet": true,
      "install_time": "5 s"
    },
    "min_skills": [ [ "weapon", 2 ], [ "melee", 1 ] ],
    "techniques": [ "RAPID" ],
    "qualities": [ [ "CUT", 2 ], [ "SAW_W", 1 ], [ "CUT_FINE", 1 ], [ "BUTCHER", 19 ] ],
    "thrown_damage": [ { "damage_type": "stab", "amount": 14 } ],
    "flags": [
      "DURABLE_MELEE",
      "SHEATH_KNIFE",
      "NPC_THROWN",
      "ALLOWS_BODY_BLOCK",
      "PUMP_RAIL_COMPATIBLE",
      "NO_SALVAGE",
      "CONDUCTIVE"
    ],
    "weapon_category": [ "KNIVES" ],
    "melee_damage": { "stab": 22 }
  },

This axe ring only allows items w/ the SHEATH_AXE flag:
[
  {
    "id": "axe_ring",
    "type": "ARMOR",
    "name": { "str": "axe ring holster" },
    "description": "A combination of leather and a metal ring to hold an axe on your waist.",
    "weight": "180 g",
    "volume": "600 ml",
    "price": 3000,
    "price_postapoc": 250,
    "material": [ "leather", "steel" ],
    "symbol": "[",
    "looks_like": "sheath",
    "color": "brown",
    "material_thickness": 1,
    "pocket_data": [
      {
        "moves": 30,
        "max_contains_volume": "3250 ml",
        "max_contains_weight": "5 kg",
        "max_item_length": "100 cm",
        "holster": true,
        "flag_restriction": [ "SHEATH_AXE" ],
        "volume_encumber_modifier": 0.3
      }
    ],
    "use_action": { "type": "holster", "holster_prompt": "Sheath axe", "holster_msg": "You sheath your %s" },
    "flags": [ "NONCONDUCTIVE", "BELTED", "BELT_CLIP", "OVERSIZE", "WATER_FRIENDLY" ],
    "armor": [ { "encumbrance": 0, "coverage": 50, "covers": [ "torso" ], "specifically_covers": [ "torso_waist" ] } ]
  },

In order to make the holster only contain the gun w/ the mod, & not the mod itself, make the min vol/length slightly bigger than the mod itself.

**Comment by Hyperseeker** [comment]
Thanks for the idea. I'll experiment with this when I start working on holsters. Will post the results here.

**Comment by PGR-14** [comment]
Welcome

**Comment by Hyperseeker** [comment]
I've just been able to confirm that this is feasible and viable.

Restricting a pocket to a flag, and then giving the flag to a gunmod, allows the pocket to retain items which have the flagged gunmod. This opens up a bunch of new possibilities regarding holsters.

@PGR-14: Thank you once again for the suggestion. I'm going to close the issue but will keep using this method with Armory in the future.

**Comment by PGR-14** [comment]
Welcome
